version: "3.3"

services:
  tomcat:
    container_name: api-rest-vol
    build: .
    network_mode: "host"
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
  client-vol-service:
    container_name: client-vol
    build: build/client-vol/
    network_mode: "host"
